spring:
  mvc:
    view:
      prefix: /templates/

  datasource:
      url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: bootweb
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      ## 连接池中的最小空闲连接
      min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 0
master:
  datasource:   #主库
    url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

cluster:
  datasource:   #从库
      url: jdbc:mysql://rm-bp1e5wj1225x3b702o.mysql.rds.aliyuncs.com:3306/dbgirl_cluster?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: Khjk2017
      driverClassName: com.mysql.jdbc.Driver



mybatis:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mars.model
  configuration:
    map-underscore-to-camel-case: true

#log
logging:
  config: classpath:logback-spring.xml
